function R = rotArbitrary(t,u_in)

u = u_in / norm(u_in);
R = [cos(t)+u(1)^2*(1-cos(t)) ...
    u(1)*u(2)*(1-cos(t))-u(3)*sin(t) ...
    u(1)*u(3)*(1-cos(t))+u(2)*sin(t); ...
    u(2)*u(1)*(1-cos(t))+u(3)*sin(t) ...
    cos(t) + u(2)^2*(1-cos(t)) ...
    u(2)*u(3)*(1-cos(t))-u(1)*sin(t); ...
    u(3)*u(1)*(1-cos(t))-u(2)*sin(t) ...
    u(3)*u(2)*(1-cos(t))+u(1)*sin(t) ...
    cos(t)+u(3)^2*(1-cos(t))
    ];

end